# rules.jl — operator map for from_sexpr
#
# Sources:
#   DiffRules.jl/src/rules.jl
#   herbie/egg-herbie/src/math.rs — neg, fabs, ceil, floor, round

import SpecialFunctions
import NaNMath
import LogExpFunctions

const OP_MAP = Dict{String, Any}(

    # General Math — binary
    "+" => (+),
    "-" => (-),
    "*" => (*),
    "/" => (/),
    "^" => (^),
    "pow" => (^),
    "atan2" => atan,
    "hypot" => hypot,
    "max" => max,
    "min" => min,
    "mod" => mod,
    "rem" => rem,
    "ldexp" => ldexp,
    "log" => log,

    # General Math — unary
    "sqrt" => sqrt,
    "cbrt" => cbrt,
    "abs" => abs,
    "abs2" => abs2,
    "inv" => inv,
    "log2" => log2,
    "log10" => log10,
    "log1p" => log1p,
    "exp" => exp,
    "exp2" => exp2,
    "exp10" => exp10,
    "expm1" => expm1,
    "sin" => sin,
    "cos" => cos,
    "tan" => tan,
    "sec" => sec,
    "csc" => csc,
    "cot" => cot,
    "sind" => sind,
    "cosd" => cosd,
    "tand" => tand,
    "secd" => secd,
    "cscd" => cscd,
    "cotd" => cotd,
    "sinpi" => sinpi,
    "cospi" => cospi,
    "asin" => asin,
    "acos" => acos,
    "atan" => atan,
    "asec" => asec,
    "acsc" => acsc,
    "acot" => acot,
    "asind" => asind,
    "acosd" => acosd,
    "atand" => atand,
    "asecd" => asecd,
    "acscd" => acscd,
    "acotd" => acotd,
    "sinh" => sinh,
    "cosh" => cosh,
    "tanh" => tanh,
    "sech" => sech,
    "csch" => csch,
    "coth" => coth,
    "asinh" => asinh,
    "acosh" => acosh,
    "atanh" => atanh,
    "asech" => asech,
    "acsch" => acsch,
    "acoth" => acoth,
    "sinc" => sinc,
    "deg2rad" => deg2rad,
    "rad2deg" => rad2deg,
    "mod2pi" => mod2pi,

    # General Math — trinary
    "muladd" => muladd,
    "fma" => fma,

    # Herbie extras — herbie/egg-herbie/src/math.rs
    "fabs" => abs,
    "ceil" => ceil,
    "floor" => floor,
    "round" => round,

    # SpecialFunctions — unary
    # DiffRules.jl/src/rules.jl
    "gamma" => SpecialFunctions.gamma,
    "loggamma" => SpecialFunctions.loggamma,
    "erf" => SpecialFunctions.erf,
    "erfinv" => SpecialFunctions.erfinv,
    "erfc" => SpecialFunctions.erfc,
    "logerfc" => SpecialFunctions.logerfc,
    "erfcinv" => SpecialFunctions.erfcinv,
    "erfi" => SpecialFunctions.erfi,
    "erfcx" => SpecialFunctions.erfcx,
    "logerfcx" => SpecialFunctions.logerfcx,
    "dawson" => SpecialFunctions.dawson,
    "digamma" => SpecialFunctions.digamma,
    "invdigamma" => SpecialFunctions.invdigamma,
    "trigamma" => SpecialFunctions.trigamma,
    "airyai" => SpecialFunctions.airyai,
    "airyaiprime" => SpecialFunctions.airyaiprime,
    "airyaix" => SpecialFunctions.airyaix,
    "airyaiprimex" => SpecialFunctions.airyaiprimex,
    "airybi" => SpecialFunctions.airybi,
    "airybiprime" => SpecialFunctions.airybiprime,
    "airybix" => SpecialFunctions.airybix,
    "airybiprimex" => SpecialFunctions.airybiprimex,
    "besselj0" => SpecialFunctions.besselj0,
    "besselj1" => SpecialFunctions.besselj1,
    "bessely0" => SpecialFunctions.bessely0,
    "bessely1" => SpecialFunctions.bessely1,
    "sinint" => SpecialFunctions.sinint,
    "cosint" => SpecialFunctions.cosint,
    "ellipk" => SpecialFunctions.ellipk,
    "ellipe" => SpecialFunctions.ellipe,
    "expint" => SpecialFunctions.expint,

    # SpecialFunctions — binary
    "erf2" => SpecialFunctions.erf,
    "besselj" => SpecialFunctions.besselj,
    "besseljx" => SpecialFunctions.besseljx,
    "besseli" => SpecialFunctions.besseli,
    "besselix" => SpecialFunctions.besselix,
    "bessely" => SpecialFunctions.bessely,
    "besselyx" => SpecialFunctions.besselyx,
    "besselk" => SpecialFunctions.besselk,
    "besselkx" => SpecialFunctions.besselkx,
    "besselh" => SpecialFunctions.besselh,
    "besselhx" => SpecialFunctions.besselhx,
    "hankelh1" => SpecialFunctions.hankelh1,
    "hankelh1x" => SpecialFunctions.hankelh1x,
    "hankelh2" => SpecialFunctions.hankelh2,
    "hankelh2x" => SpecialFunctions.hankelh2x,
    "polygamma" => SpecialFunctions.polygamma,
    "beta" => SpecialFunctions.beta,
    "logbeta" => SpecialFunctions.logbeta,
    "expint2" => SpecialFunctions.expint,
    "zeta" => SpecialFunctions.zeta,

    # NaNMath — unary
    # DiffRules.jl/src/rules.jl
    "nan_sqrt" => NaNMath.sqrt,
    "nan_sin" => NaNMath.sin,
    "nan_cos" => NaNMath.cos,
    "nan_tan" => NaNMath.tan,
    "nan_asin" => NaNMath.asin,
    "nan_acos" => NaNMath.acos,
    "nan_acosh" => NaNMath.acosh,
    "nan_atanh" => NaNMath.atanh,
    "nan_log" => NaNMath.log,
    "nan_log2" => NaNMath.log2,
    "nan_log10" => NaNMath.log10,
    "nan_log1p" => NaNMath.log1p,
    "nan_lgamma" => NaNMath.lgamma,

    # NaNMath — binary
    "nan_pow" => NaNMath.pow,
    "nan_max" => NaNMath.max,
    "nan_min" => NaNMath.min,

    # LogExpFunctions — unary
    # DiffRules.jl/src/rules.jl
    "xlogx" => LogExpFunctions.xlogx,
    "logistic" => LogExpFunctions.logistic,
    "logit" => LogExpFunctions.logit,
    "log1psq" => LogExpFunctions.log1psq,
    "log1pexp" => LogExpFunctions.log1pexp,
    "log1mexp" => LogExpFunctions.log1mexp,
    "log2mexp" => LogExpFunctions.log2mexp,
    "logexpm1" => LogExpFunctions.logexpm1,
    "log1pmx" => LogExpFunctions.log1pmx,
    "logmxp1" => LogExpFunctions.logmxp1,

    # LogExpFunctions — binary
    "xlogy" => LogExpFunctions.xlogy,
    "logaddexp" => LogExpFunctions.logaddexp,
    "logsubexp" => LogExpFunctions.logsubexp,
    "xlog1py" => LogExpFunctions.xlog1py
)
